version: "3.3"

services:
  api-gateway:
    build: ./babyapinest-api-gateway
    container_name: api-gateway
    command: npm run start:dev
    restart: unless-stopped
    ports: 
      - "3001:3001"
    networks: 
      - babyapinest
    depends_on: 
      - api-gateway-db
  
  api-gateway-db:
    image: mongo:latest
    container_name: api-gateway-db
    volumes:
        - api-dateway-db-mongo:/data/db
    networks: 
      - babyapinest

networks:
  babyapinest:
    driver: bridge


volumes:
  api-dateway-db-mongo:
